version: "3.1"

services:

  db:
    image: postgres:latest
    container_name: pizza_db
    restart: always
    environment:
      #- POSTGRES_DB=postgres
      #- POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pizza_data.sql:/docker-entrypoint-initdb.d/pizza_data.sql
    ports:
      - "5432:5432"