spring:
  application:
    name: "email-service"
  devtools:
    restart:
      enabled: false

server:
  port: 0

mail:
  host: "smtp.gmail.com"
  port: 587
  login: "login"
  password: "password"
  debug: "true"
