spring:
  application:
    name: "information-service"
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  devtools:
    restart:
      enabled: false
  data:
    rest:
      detection-strategy: annotated
      default-media-type: application/json
      base-path: "/api"

server:
  port: 0